language: go

go:
  - 1.9.x

before_install:
  - go get -t -v ./...

script: 
  - echo 'mode: atomic' > coverage.txt && go list ./... | xargs -n1 -I{} sh -c 'go test -covermode=atomic -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.txt' && rm coverage.tmp

after_success:
  - bash <(curl -s https://codecov.io/bash)